--Magnitude Analysis 

--total cust by countries

select 
country,
count(customer_key) as total_customers
from gold.dim_customers
group by country
order by total_customers desc;


--total cust by gender

select 
gender,
count(customer_key) as total_customers
from gold.dim_customers
group by gender
order by total_customers desc;


--total products by category

select 
category,
count(product_key) as total_products
from gold.dim_products
group by category
order by total_products desc;

--avg cost in each category

select 
category,
avg(product_key) as avg_cost
from gold.dim_products
group by category
order by avg_cost desc;

-- tot revenue for each category

select 
p.category,
sum(f.sales_amount) total_revenue
from gold.fact_sales f
left join gold.dim_products p
on p.product_key = f.product_key
group by p.categorydd
order by total_revenue desc;


--revenue generated by each cust

SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across countries?
SELECT
    c.country,
    SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;




